Практическое задание №1
Абдуллаева Вера группа 494а

1. Создайте массив arr_1 размером 3х4, все элементы которого равны 3.

In [1]:
import numpy as np
arr_1 = np.full((3, 4), 3)
arr_1

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

2. Создайте массив arr_2, заполненный случайными целыми числами от 0 до 9, размером 2х4.

In [2]:
arr_2 = np.random.randint(0, 9, (2, 4))
arr_2

array([[1, 3, 6, 3],
       [3, 6, 3, 6]])

3. Выведите на экран количество элементов в созданных массивах arr_1 и arr_2.

In [3]:
print("размер массива arr_1: ", arr_1.size)
print("размер массива arr_2: ", arr_2.size)

размер массива arr_1:  12
размер массива arr_2:  8


4. Соедините массивы arr_1 и arr_2 по нулевой оси.

In [4]:
np.concatenate([arr_1, arr_2])

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [1, 3, 6, 3],
       [3, 6, 3, 6]])

5. Создайте массив arr_3 из кортежа чисел (1, 8, 6, 5, 8, 3) с помощью функции np.array().

In [6]:
arr_3 = np.array((1, 8, 6, 5, 8, 3))
arr_3

array([1, 8, 6, 5, 8, 3])

6. Умножьте каждый элемент массива arr_3 на число 3 и прибавьте к каждому элементу 1. Результат запишите в новый массив arr_4.

In [9]:
arr_4 = arr_3 * 3 + 1
arr_4

array([ 4, 25, 19, 16, 25, 10])

7. Преобразуйте масcив arr_3 к двумерному массиву 2х3. Результат запишите в массив arr_5.

In [10]:
arr_5 = arr_3.reshape((2, 3))
arr_5

array([[1, 8, 6],
       [5, 8, 3]])

8. Определите минимальные элементы массива arr_5 вдоль первой оси.

In [11]:
arr_5.min(axis = 1)

array([1, 3])

9. Вычислите среднее арифметическое всех элементов массива arr_5.

In [12]:
arr_5.mean()

5.166666666666667

10. Создайте массив arr_6, состоящий из квадратов чисел от 0 до 10.

In [13]:
arr_6 = (np.arange(0,10)) ** 2
arr_6

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

11. Выведите каждый второй элемент массива arr_6.

In [14]:
arr_6[1::2]

array([ 1,  9, 25, 49, 81], dtype=int32)

12. Выведите элементы массива arr_6 в обратном порядке.

In [15]:
arr_6[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0], dtype=int32)

13. Каждому второму элементу массива arr_6 присвойте значение 2.

In [16]:
arr_6[1::2] = 2
arr_6

array([ 0,  2,  4,  2, 16,  2, 36,  2, 64,  2], dtype=int32)

14. Проверьте, есть ли в массиве arr_6 значение 49.

In [18]:
condition = (arr_6 == 49)
np.extract(condition, arr_6)

array([], dtype=int32)

15. Создайте двумерный массив А, состоящий из положительных и отрицательных чисел. Из массива A выберите все отрицательные элементы и запишите их в одномерный массив B.

In [32]:
A = np.random.randint(-10, 10, (3, 3))
condition = (A < 0)
B = np.extract(condition, A)
B

array([-4, -1, -8, -9, -9, -9])